### ISSUE TITLE
Error loading type library/DLL - Outlook 2016

### ISSUE THREAD

**Issue by srrsparky** [Dashbrd/CalendarSyncplus#47]
Hi,
This app appears to have stopped working for me - looks like it can't connect to Outlook anymore. I am running version 1.4.17084.2 and outlook is Version 1710, build 8625.2055.

In the settings, it doesn't load my outlook mailboxes to select a specific calendar. Previous versions that were already setup started not working with "Read Failed" and the log of the below. Most recent log file attached.

System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Outlook.ApplicationClass.GetNamespace(String Type)
   at CalendarSyncPlus.OutlookServices.Calendar.OutlookCalendarService.GetOutlookApplication(Boolean& disposeOutlookInstances, Application& application, NameSpace& nameSpace, String profileName)
   at CalendarSyncPlus.OutlookServices.Calendar.OutlookCalendarService.GetOutlookEntriesForSelectedTimeRange(DateTime startDate, DateTime endDate, Boolean skipPrivateEntries

[CalSyncPlusLog.zip](https://github.com/Dashbrd/CalendarSyncplus/files/1389649/CalSyncPlusLog.zip)

**Comment by srrsparky** [comment]
"Repaired" my office installation and the program seems to be working again.
